import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/site/PageHero";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [{ title: "Privacy Policy | CareNest" }, { name: "description", content: "How CareNest collects, uses and protects your personal information." }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <>
      <PageHero eyebrow="Legal" title="Privacy Policy" subtitle="Last updated: January 2026" />
      <section className="container-page py-16 max-w-3xl prose prose-neutral">
        <div className="space-y-6 text-muted-foreground leading-relaxed">
          <div><h2 className="text-foreground font-bold text-xl">Information we collect</h2><p>We collect information you provide directly (name, contact, profile info) and information generated by your use of CareNest (bookings, messages, reviews).</p></div>
          <div><h2 className="text-foreground font-bold text-xl">How we use it</h2><p>To match families with care workers, process payments, verify identity, prevent fraud, improve our service and comply with legal obligations.</p></div>
          <div><h2 className="text-foreground font-bold text-xl">Sharing</h2><p>We never sell your data. We share information only with the parties needed to deliver care (e.g. between matched families and workers) or with service providers under contract.</p></div>
          <div><h2 className="text-foreground font-bold text-xl">Your rights</h2><p>You may access, correct, export or delete your personal information at any time via your account settings or by contacting us.</p></div>
          <div><h2 className="text-foreground font-bold text-xl">Contact</h2><p>For privacy questions, email privacy@carenest.example.</p></div>
        </div>
      </section>
    </>
  );
}
